remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [Filma Bem Bucket]
description: [This is my personal application bucket for scoop. Including my own apps and games. 3rd party apps will only be updated when i have time]
show_downloads: [false]
